name: DeployFirebaseApp

on:
  workflow_dispatch:
      inputs:
        release_note:
          type: string
          required: true
          default: 'Manual Debug Build'
          description: 'Release Notes'

jobs:
  DeployFirebaseApp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Remove google_application_credentials.json
        run: rm google_application_credentials.json
        continue-on-error: true

      - name: Remove RELEASE NOTE file
        run: rm release_notes.txt
        continue-on-error: true

      - name: Create RELEASE NOTE file
        run: echo "${{ inputs.release_note }}" >> release_notes.txt

      - name: Create google_application_credentials.json
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS" >> google_application_credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.DEV_CREDENTIAL_FILE_CONTENT }}

      - name: Deploy App
        run: ./gradlew assembleDebug appDistributionUploadDebug
