name: DeployFirebaseApp

on:
  workflow_dispatch:
    inputs:
      release_note:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'
      tester_groups:
        type: string
        required: true
        default: 'st-testers'
        description: 'Tester groups'

jobs:
  deploy-firebase-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

      - name: Set up Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.1.0

      - name: Remove google_application_credentials.json
        run: rm google_application_credentials.json
        continue-on-error: true

      - name: Remove RELEASE NOTE file
        run: rm release_notes.txt
        continue-on-error: true

      - name: Remove TESTER GROUPS file
        run: rm tester_groups.txt
        continue-on-error: true

      - name: Create RELEASE NOTE file
        run: echo "${{ inputs.release_note }}" >> release_notes.txt

      - name: Create TESTER GROUPS file
        run: echo "${{ inputs.tester_groups }}" >> tester_groups.txt

      - name: Create google_application_credentials.json
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS" >> google_application_credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.DEV_CREDENTIAL_FILE_CONTENT }}

      - name: Deploy App
        run: ./gradlew assembleDebug appDistributionUploadDebug
